project:
  type: website
  execute-dir: project

website:
  title: "James H Wade"
  site-url: https://jameshwade.com
  favicon: images/favicon.ico
  twitter-card: true
  navbar:
    background: light
    search: true
    right:
      - about.qmd
      - href: talks.qmd
        text: Talks
      - icon: rss
        href: index.xml
      - icon: youtube
        href: https://youtube.com/@james-h-wade
      - icon: twitter
        href: https://twitter.com/jameshwade
      - icon: linkedin
        href: https://linkedin.com/in/james-h-wade
      - icon: github
        href: https://github.com/jameshwade
      - icon: mastodon
        href: https://fosstodon.org/@jameshwade
  page-footer:
    left: "© 2023–2026 James Wade. Text and images licensed [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), code [MIT](https://choosealicense.com/licenses/mit/) unless otherwise noted."

format:
  html:
    theme:
      - brand
      - custom.scss
    highlight-style: atom-one-dark
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap" rel="stylesheet">

# comments:
#   giscus:
#     repo: jameshwade/jameshwadedotcom

execute:
  freeze: auto
